language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install requests
  - pip install coverage
  - pip install codecov
script:
  - python -m coverage run test_classes.py
after_success:
  - python -m codecov